language: java
deploy:
  provider: heroku
  api_key:
    secure: aSE2I4vhIM6GfQo2DWdRXxZDxUEKQghlomihS0QSAT56WjC78tjfE+eukm88HeArjc/bh2qqPzFTwfQi1uwNS+t6sQXam6LNwhTua1nWdLLqRfucK1awAWUh1xx/ZWRZFIuo0kw7aZBeDwO/O33H89V6xYrMj3VT+K69J7HdicScz8LkDWCa0Dn/4r+bH6Mrbh0fKPOCJraRXzSiCX3tshpzM4qPZd6syzb+kLOc7E5rxvhK5KYCOZs9KCx1WIsNYOSS+aZrJG18+vpytjZ+asWZ4zyVbDX8RCwAXQy2wIpj5CeAbTewf34yb+kmBmyN0AKQgR3NnkeGs40zc/1vQI43d/0Loz3iM7MYHASWSSKsp5MBLLSa1tfrq7zzoiCpBFT11GaGAXqkPopnNm/v51mc65OPvaWxQaEVeKO5ZD9ByvAJmzItCWbU2fzeI5O8f9cXDYpoZFdz2UdmpHz/7jx21jr6Z0JATcBuU7Z6dQgqSQGRYK+YosYsgo81uSSaC4GkPwAHtNOBen/8CJJCHgcI7PIni2OS4I0rhtIawKuqPMGInUH8TxVjSNTi7EZIPO79ME+0ZlESMrc5bB/6H9rWeyRZ1S6s4ZytW4ve0LW5FjeUdGn8raqgPZDd+TG7GdrwXwudlYMg7mQR24rSDdxH1RYL5Mho0eijQYbY8j0=
sudo: required
dist: trusty
addons:
  chrome: stable
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
after_success:
  - ./gradlew cobertura coveralls